items = items.map(item => {
    return item.querySelectorAll('.price-amount').length > 1 ? {
        "number": Number(item.querySelector('.item-title').textContent.trim().split(/^#(\d+) /)[1]),
        "name": item.querySelector('.item-title').textContent.trim().split(/^#(\d+) /)[2],
        "ingredients": item.firstElementChild.textContent.split('\n')[1].split(/,\s/),
        "price": {
            "half": Number(item.querySelectorAll('.price-amount')[0].textContent),
            "whole": Number(item.querySelectorAll('.price-amount')[1].textContent)
        }
    } : {
            "number": Number(item.querySelector('.item-title').textContent.trim().split(/^#(\d+) /)[1]),
            "name": item.querySelector('.item-title').textContent.trim().split(/^#(\d+) /)[2],
            "ingredients": item.firstElementChild.textContent.split('\n')[1].split(/,\s/),
            "price": Number(item.querySelector('.price-amount').textContent)
        }
});

const categories = [{
    "name": "cheese",
    "options": [
      "american",
      "cheddar",
      "mozzarella",
      "muenster",
      "pepper jack",
      "provolone",
      "smoked gouda",
      "swiss"
    ]
  },
  {
    "name": "meat",
    "options": [
      "bacon",
      "breaded chicken cutlet",
      "burger",
      "capicola",
      "chicken fingers",
      "chicken salad",
      "chopped steak",
      "corned beef",
      "fried bologna",
      "grilled chicken",
      "ham",
      "italian sausage patty",
      "meatballs",
      "pastrami",
      "pepperoni",
      "roast beef",
      "roasted pork loin",
      "salami",
      "sausage patty",
      "tuna",
      "turkey"
    ]
  },
  {
    "name": "condiments",
    "options": [
      "au jus",
      "balsamic dressing",
      "basil mayo",
      "bbq sauce",
      "bleu cheese",
      "cajun ranch",
      "cheese sauce",
      "guacamole",
      "honey mustard",
      "honey stinging garlic sauce",
      "horsey mayo",
      "hot sauce",
      "hummus",
      "italian dressing",
      "jalapeno mayo",
      "ketchup",
      "marinara sauce",
      "mayo",
      "medium sauce",
      "mustard",
      "oil",
      "olive spread",
      "pesto mayo",
      "roasted red pepper mayo",
      "russian dressing",
      "sriracha mayo",
      "sweet chili sauce"
    ]
  },
  {
    "name": "misc",
    "options": [
      "cool ranch doritos",
      "french fries",
      "mesquite bbq chips",
      "mozzarella sticks",
      "nacho cheese doritos",
      "toasted almonds"
    ]
  },
  {
    "name": "fruits and vegetables",
    "options": [
      "coleslaw",
      "cucumber",
      "eggplant",
      "hot peppers",
      "jalapenos",
      "lettuce",
      "mesculin mix",
      "mushrooms",
      "onion",
      "peppers",
      "pickles",
      "portobello mushrooms",
      "red grapes",
      "red onion",
      "roasted red peppers",
      "roasted vegetables",
      "sauerkraut",
      "sauteed hot peppers",
      "sauteed onions",
      "sweet chili coleslaw",
      "spinach",
      "tomato"
    ]
  },
  {
    "name": "bread",
    "options": [
      "garlic sub",
      "grilled rye",
      "grilled garlic sub",
      "kimmel weck roll",
      "rye",
      "toasted garlic sub",
      "toasted sub"
    ]
  }
]


const ingredients = [
    "american",
    "au jus",
    "bacon",
    "balsamic dressing",
    "basil mayo",
    "bbq sauce",
    "bleu cheese",
    "breaded chicken cutlet",
    "burger",
    "cajun ranch",
    "capicola",
    "cheddar",
    "cheese sauce",
    "chicken fingers",
    "chicken salad",
    "chopped steak",
    "coleslaw",
    "cool ranch doritos",
    "corned beef",
    "cucumber",
    "eggplant",
    "french fries",
    "fried bologna",
    "garlic sub",
    "grilled chicken",
    "grilled rye",
    "grilled garlic sub",
    "guacamole",
    "ham",
    "honey mustard",
    "honey stinging garlic sauce",
    "horsey mayo",
    "hot peppers",
    "hot sauce",
    "hummus",
    "italian dressing",
    "italian sausage patty",
    "jalapeno mayo",
    "jalapenos",
    "ketchup",
    "kimmel weck roll",
    "lettuce",
    "marinara sauce",
    "mayo",
    "meatballs",
    "medium sauce",
    "mesculin mix",
    "mesquite bbq chips",
    "mozzarella",
    "mozzarella sticks",
    "muenster cheese",
    "mushrooms",
    "mustard",
    "nacho cheese doritos",
    "oil",
    "olive spread",
    "onion",
    "pastrami",
    "pepper jack",
    "pepperoni",
    "peppers",
    "pesto mayo",
    "pickles",
    "portobello mushrooms",
    "provolone",
    "red grapes",
    "red onion",
    "roast beef",
    "roasted pork loin",
    "roasted red pepper mayo",
    "roasted red peppers",
    "roasted vegetables",
    "russian dressing",
    "rye",
    "salami",
    "sauerkraut",
    "sausage patty",
    "sauteed hot peppers",
    "sauteed onions",
    "smoked gouda",
    "spinach",
    "sriracha mayo",
    "sweet chili coleslaw",
    "sweet chili sauce",
    "swiss",
    "toasted almonds",
    "toasted garlic sub",
    "toasted sub",
    "tomato",
    "tuna",
    "turkey"
]